version: '3'
services:
  web:
    build: zambia-web
    container_name: zambia-web
    ports: 
    -  "18080:80"
    links:
    - db 
    volumes:
    - ../webpages:/var/www/html/zambiademo
    - ../scripts:/zambia/scripts
  db:
    image: mysql:5.5
    container_name: zambia-db
    volumes:
    - ./mysql-db:/var/lib/mysql
    - ..:/zambia
    # initial db setup lines
    # environment:
    #   MYSQL_ROOT_PASSWORD: password
    #   MYSQL_DATABASE: zambiademo
    #   MYSQL_USER: zambiademo
    #   MYSQL_PASSWORD: 4fandom
